#!/usr/bin/env bash

INSTALL_BASE_URL="https://raw.githubusercontent.com/lucasls/protoc-wrapper"

basedir=$(dirname "$0")

lower() {
    echo $1 | tr '[:upper:]' '[:lower:]'
}

print() {
    printf "$1" >&2
}

println() {
    echo "$1" >&2
}

configure() {
    print "Target protoc version: "
    read version

    echo "protoc_version=$version" > $basedir/protocw.env
    println "Version set to $version, to change either edit protocw.env or run protocw --configure"
    exit
}

help() {
    println "** Protoc Wrapper Help: **"
    println ""
    println "  --configure    Sets up what version of protoc to use"
    println "  --self-update  Updates Protoc Wrapper to the newest version"

    if [ -z $protoc_version ]
    then
        exit
    fi

    println ""
    println "** Protoc Help **"
    println ""
}

self_update() {
    println "Starting Protoc Wrapper self update..."
    println ""

    eval "$(curl -fsSL $INSTALL_BASE_URL/install.sh)"
    exit
}

# Start

if [ "$1" = "--configure" ]
then
    configure
fi

if [ "$1" = "--self-update" ]
then
    self_update
fi

touch $basedir/protocw.env
source $basedir/protocw.env

if [ "$1" = "--help" ]
then
    help
fi

if [ -z $protoc_version ]
then
    println "protoc_version not set in protocw.env"
    exit -1
fi

mkdir -p "$basedir/.protocw"
filename="$basedir/.protocw/protoc-$protoc_version"

if [ ! -f $filename ]
then
    if [ $(lower $(uname))  = "darwin" ]
    then
        osname="osx"
    else
        osname="linux"
    fi
    osarch=$(uname -m)

    print "Downloading Protoc $protoc_version... "
    curl "https://repo1.maven.org/maven2/com/google/protobuf/protoc/$protoc_version/protoc-$protoc_version-$osname-$osarch.exe" -o $filename --fail --silent

    last_error=$?

    if [ $last_error -ne 0 ]; then
        println "Error"
        println "Could not download protoc, please check if version $protoc_version is a valid version in protoc Maven Repository"
        exit $last_error
    fi

    println "Done"

    chmod +x $filename
fi

"$filename" "$@"